# Generated by Django 4.0.6 on 2022-08-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(max_length=350, null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha',
            field=models.CharField(default=2, max_length=200, verbose_name='Fecha de Inicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
    ]
