# Generated by Django 4.0.6 on 2022-08-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0002_evento_descripcion_evento_fecha_alter_evento_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
